CONFLICTS = {
  "accent-color": "",
  "align-content": "",
  "align-items": "",
  "align-self": "",
  "align-tracks": "",
  "all": "",
  "animation": [
    "animation-name",
    "animation-duration",
    "animation-timing-function",
    "animation-delay",
    "animation-direction",
    "animation-iteration-count",
    "animation-fill-mode",
    "animation-play-state",
    "animation-timeline",
  ],
  "animation-composition": "",
  "animation-delay": "",
  "animation-direction": "",
  "animation-duration": "",
  "animation-fill-mode": "",
  "animation-iteration-count": "",
  "animation-name": "",
  "animation-play-state": "",
  "animation-range": [
    "animation-range-start",
    "animation-range-end",
  ],
  "animation-range-end": "",
  "animation-range-start": "",
  "animation-timing-function": "",
  "animation-timeline": "",
  "appearance": "",
  "aspect-ratio": "",
  "azimuth": "",
  "backdrop-filter": "",
  "backface-visibility": "",
  "background": [
    "background-image",
    "background-position",
    "background-size",
    "background-repeat",
    "background-origin",
    "background-clip",
    "background-attachment",
    "background-color",
  ],
  "background-attachment": "",
  "background-blend-mode": "",
  "background-clip": "",
  "background-color": "",
  "background-image": "",
  "background-origin": "",
  "background-position": [
    "background-position-x",
    "background-position-y",
  ],
  "background-position-x": "",
  "background-position-y": "",
  "background-repeat": "",
  "background-size": "",
  "block-size": "",
  "border": [
    "border-width",
    "border-style",
    "border-color",
  ],
  "border-block": [
    "border-block-width",
    "border-block-style",
    "border-block-color",
  ],
  "border-block-color": "",
  "border-block-style": "",
  "border-block-width": "",
  "border-block-end": [
    "border-top-width",
    "border-top-style",
    "border-top-color",
  ],
  "border-block-end-color": "",
  "border-block-end-style": "",
  "border-block-end-width": "",
  "border-block-start": [
    "border-width",
    "border-style",
    "border-block-start-color",
  ],
  "border-block-start-color": "",
  "border-block-start-style": "",
  "border-block-start-width": "",
  "border-bottom": [
    "border-bottom-width",
    "border-bottom-style",
    "border-bottom-color",
  ],
  "border-bottom-color": "",
  "border-bottom-left-radius": "",
  "border-bottom-right-radius": "",
  "border-bottom-style": "",
  "border-bottom-width": "",
  "border-collapse": "",
  "border-color": [
    "border-bottom-color",
    "border-left-color",
    "border-right-color",
    "border-top-color",
  ],
  "border-end-end-radius": "",
  "border-end-start-radius": "",
  "border-image": [
    "border-image-outset",
    "border-image-repeat",
    "border-image-slice",
    "border-image-source",
    "border-image-width",
  ],
  "border-image-outset": "",
  "border-image-repeat": "",
  "border-image-slice": "",
  "border-image-source": "",
  "border-image-width": "",
  "border-inline": [
    "border-inline-width",
    "border-inline-style",
    "border-inline-color",
  ],
  "border-inline-end": [
    "border-width",
    "border-style",
    "border-inline-end-color",
  ],
  "border-inline-color": "",
  "border-inline-style": "",
  "border-inline-width": "",
  "border-inline-end-color": "",
  "border-inline-end-style": "",
  "border-inline-end-width": "",
  "border-inline-start": [
    "border-width",
    "border-style",
    "border-inline-start-color",
  ],
  "border-inline-start-color": "",
  "border-inline-start-style": "",
  "border-inline-start-width": "",
  "border-left": [
    "border-left-width",
    "border-left-style",
    "border-left-color",
  ],
  "border-left-color": "",
  "border-left-style": "",
  "border-left-width": "",
  "border-radius": [
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "border-top-left-radius",
    "border-top-right-radius",
  ],
  "border-right": [
    "border-right-width",
    "border-right-style",
    "border-right-color",
  ],
  "border-right-color": "",
  "border-right-style": "",
  "border-right-width": "",
  "border-spacing": "",
  "border-start-end-radius": "",
  "border-start-start-radius": "",
  "border-style": [
    "border-bottom-style",
    "border-left-style",
    "border-right-style",
    "border-top-style",
  ],
  "border-top": [
    "border-top-width",
    "border-top-style",
    "border-top-color",
  ],
  "border-top-color": "",
  "border-top-left-radius": "",
  "border-top-right-radius": "",
  "border-top-style": "",
  "border-top-width": "",
  "border-width": [
    "border-bottom-width",
    "border-left-width",
    "border-right-width",
    "border-top-width",
  ],
  "bottom": "",
  "box-align": "",
  "box-decoration-break": "",
  "box-direction": "",
  "box-flex": "",
  "box-flex-group": "",
  "box-lines": "",
  "box-ordinal-group": "",
  "box-orient": "",
  "box-pack": "",
  "box-shadow": "",
  "box-sizing": "",
  "break-after": "",
  "break-before": "",
  "break-inside": "",
  "caption-side": "",
  "caret": [
    "caret-color",
    "caret-shape",
  ],
  "caret-color": "",
  "caret-shape": "",
  "clear": "",
  "clip": "",
  "clip-path": "",
  "color": "",
  "color-scheme": "",
  "column-count": "",
  "column-fill": "",
  "column-gap": "",
  "column-rule": [
    "column-rule-color",
    "column-rule-style",
    "column-rule-width",
  ],
  "column-rule-color": "",
  "column-rule-style": "",
  "column-rule-width": "",
  "column-span": "",
  "column-width": "",
  "columns": [
    "column-width",
    "column-count",
  ],
  "contain": "",
  "contain-intrinsic-size": [
    "contain-intrinsic-width",
    "contain-intrinsic-height",
  ],
  "contain-intrinsic-block-size": "",
  "contain-intrinsic-height": "",
  "contain-intrinsic-inline-size": "",
  "contain-intrinsic-width": "",
  "container": [
    "container-name",
    "container-type",
  ],
  "container-name": "",
  "container-type": "",
  "content": "",
  "content-visibility": "",
  "counter-increment": "",
  "counter-reset": "",
  "counter-set": "",
  "cursor": "",
  "direction": "",
  "display": "",
  "empty-cells": "",
  "filter": "",
  "flex": [
    "flex-grow",
    "flex-shrink",
    "flex-basis",
  ],
  "flex-basis": "",
  "flex-direction": "",
  "flex-flow": [
    "flex-direction",
    "flex-wrap",
  ],
  "flex-grow": "",
  "flex-shrink": "",
  "flex-wrap": "",
  "float": "",
  "font": [
    "font-style",
    "font-variant",
    "font-weight",
    "font-stretch",
    "font-size",
    "line-height",
    "font-family",
  ],
  "font-family": "",
  "font-feature-settings": "",
  "font-kerning": "",
  "font-language-override": "",
  "font-optical-sizing": "",
  "font-palette": "",
  "font-variation-settings": "",
  "font-size": "",
  "font-size-adjust": "",
  "font-smooth": "",
  "font-stretch": "",
  "font-style": "",
  "font-synthesis": "",
  "font-synthesis-position": "",
  "font-synthesis-small-caps": "",
  "font-synthesis-style": "",
  "font-synthesis-weight": "",
  "font-variant": "",
  "font-variant-alternates": "",
  "font-variant-caps": "",
  "font-variant-east-asian": "",
  "font-variant-emoji": "",
  "font-variant-ligatures": "",
  "font-variant-numeric": "",
  "font-variant-position": "",
  "font-weight": "",
  "forced-color-adjust": "",
  "gap": [
    "row-gap",
    "column-gap",
  ],
  "grid": [
    "grid-template-rows",
    "grid-template-columns",
    "grid-template-areas",
    "grid-auto-rows",
    "grid-auto-columns",
    "grid-auto-flow",
    "grid-column-gap",
    "grid-row-gap",
    "column-gap",
    "row-gap",
  ],
  "grid-area": [
    "grid-row-start",
    "grid-column-start",
    "grid-row-end",
    "grid-column-end",
  ],
  "grid-auto-columns": "",
  "grid-auto-flow": "",
  "grid-auto-rows": "",
  "grid-column": [
    "grid-column-start",
    "grid-column-end",
  ],
  "grid-column-end": "",
  "grid-column-gap": "",
  "grid-column-start": "",
  "grid-gap": [
    "grid-row-gap",
    "grid-column-gap",
  ],
  "grid-row": [
    "grid-row-start",
    "grid-row-end",
  ],
  "grid-row-end": "",
  "grid-row-gap": "",
  "grid-row-start": "",
  "grid-template": [
    "grid-template-columns",
    "grid-template-rows",
    "grid-template-areas",
  ],
  "grid-template-areas": "",
  "grid-template-columns": "",
  "grid-template-rows": "",
  "hanging-punctuation": "",
  "height": "",
  "hyphenate-character": "",
  "hyphenate-limit-chars": "",
  "hyphens": "",
  "image-orientation": "",
  "image-rendering": "",
  "image-resolution": "",
  "ime-mode": "",
  "initial-letter": "",
  "initial-letter-align": "",
  "inline-size": "",
  "input-security": "",
  "inset": [
    "top",
    "bottom",
    "left",
    "right",
  ],
  "inset-block": [
    "inset-block-start",
    "inset-block-end",
  ],
  "inset-block-end": "",
  "inset-block-start": "",
  "inset-inline": [
    "inset-inline-start",
    "inset-inline-end",
  ],
  "inset-inline-end": "",
  "inset-inline-start": "",
  "isolation": "",
  "justify-content": "",
  "justify-items": "",
  "justify-self": "",
  "justify-tracks": "",
  "left": "",
  "letter-spacing": "",
  "line-break": "",
  "line-clamp": "",
  "line-height": "",
  "line-height-step": "",
  "list-style": [
    "list-style-image",
    "list-style-position",
    "list-style-type",
  ],
  "list-style-image": "",
  "list-style-position": "",
  "list-style-type": "",
  "margin": [
    "margin-bottom",
    "margin-left",
    "margin-right",
    "margin-top",
  ],
  "margin-block": [
    "margin-block-start",
    "margin-block-end",
  ],
  "margin-block-end": "",
  "margin-block-start": "",
  "margin-bottom": "",
  "margin-inline": [
    "margin-inline-start",
    "margin-inline-end",
  ],
  "margin-inline-end": "",
  "margin-inline-start": "",
  "margin-left": "",
  "margin-right": "",
  "margin-top": "",
  "margin-trim": "",
  "mask": [
    "mask-image",
    "mask-mode",
    "mask-repeat",
    "mask-position",
    "mask-clip",
    "mask-origin",
    "mask-size",
    "mask-composite",
  ],
  "mask-border": [
    "mask-border-mode",
    "mask-border-outset",
    "mask-border-repeat",
    "mask-border-slice",
    "mask-border-source",
    "mask-border-width",
  ],
  "mask-border-mode": "",
  "mask-border-outset": "",
  "mask-border-repeat": "",
  "mask-border-slice": "",
  "mask-border-source": "",
  "mask-border-width": "",
  "mask-clip": "",
  "mask-composite": "",
  "mask-image": "",
  "mask-mode": "",
  "mask-origin": "",
  "mask-position": "",
  "mask-repeat": "",
  "mask-size": "",
  "mask-type": "",
  "masonry-auto-flow": "",
  "math-depth": "",
  "math-shift": "",
  "math-style": "",
  "max-block-size": "",
  "max-height": "",
  "max-inline-size": "",
  "max-lines": "",
  "max-width": "",
  "min-block-size": "",
  "min-height": "",
  "min-inline-size": "",
  "min-width": "",
  "mix-blend-mode": "",
  "object-fit": "",
  "object-position": "",
  "offset": [
    "offset-position",
    "offset-path",
    "offset-distance",
    "offset-anchor",
    "offset-rotate",
  ],
  "offset-anchor": "",
  "offset-distance": "",
  "offset-path": "",
  "offset-position": "",
  "offset-rotate": "",
  "opacity": "",
  "order": "",
  "orphans": "",
  "outline": [
    "outline-color",
    "outline-width",
    "outline-style",
  ],
  "outline-color": "",
  "outline-offset": "",
  "outline-style": "",
  "outline-width": "",
  "overflow": [
    "overflow-x",
    "overflow-y",
  ],
  "overflow-anchor": "",
  "overflow-block": "",
  "overflow-clip-box": "",
  "overflow-clip-margin": "",
  "overflow-inline": "",
  "overflow-wrap": "",
  "overflow-x": "",
  "overflow-y": "",
  "overlay": "",
  "overscroll-behavior": [
    "overscroll-behavior-x",
    "overscroll-behavior-y",
  ],
  "overscroll-behavior-block": "",
  "overscroll-behavior-inline": "",
  "overscroll-behavior-x": "",
  "overscroll-behavior-y": "",
  "padding": [
    "padding-bottom",
    "padding-left",
    "padding-right",
    "padding-top",
  ],
  "padding-block": [
    "padding-block-start",
    "padding-block-end",
  ],
  "padding-block-end": "",
  "padding-block-start": "",
  "padding-bottom": "",
  "padding-inline": [
    "padding-inline-start",
    "padding-inline-end",
  ],
  "padding-inline-end": "",
  "padding-inline-start": "",
  "padding-left": "",
  "padding-right": "",
  "padding-top": "",
  "page": "",
  "page-break-after": "",
  "page-break-before": "",
  "page-break-inside": "",
  "paint-order": "",
  "perspective": "",
  "perspective-origin": "",
  "place-content": [
    "align-content",
    "justify-content",
  ],
  "place-items": [
    "align-items",
    "justify-items",
  ],
  "place-self": [
    "align-self",
    "justify-self",
  ],
  "pointer-events": "",
  "position": "",
  "print-color-adjust": "",
  "quotes": "",
  "resize": "",
  "right": "",
  "rotate": "",
  "row-gap": "",
  "ruby-align": "",
  "ruby-merge": "",
  "ruby-position": "",
  "scale": "",
  "scrollbar-color": "",
  "scrollbar-gutter": "",
  "scrollbar-width": "",
  "scroll-behavior": "",
  "scroll-margin": [
    "scroll-margin-bottom",
    "scroll-margin-left",
    "scroll-margin-right",
    "scroll-margin-top",
  ],
  "scroll-margin-block": [
    "scroll-margin-block-start",
    "scroll-margin-block-end",
  ],
  "scroll-margin-block-start": "",
  "scroll-margin-block-end": "",
  "scroll-margin-bottom": "",
  "scroll-margin-inline": [
    "scroll-margin-inline-start",
    "scroll-margin-inline-end",
  ],
  "scroll-margin-inline-start": "",
  "scroll-margin-inline-end": "",
  "scroll-margin-left": "",
  "scroll-margin-right": "",
  "scroll-margin-top": "",
  "scroll-padding": [
    "scroll-padding-bottom",
    "scroll-padding-left",
    "scroll-padding-right",
    "scroll-padding-top",
  ],
  "scroll-padding-block": [
    "scroll-padding-block-start",
    "scroll-padding-block-end",
  ],
  "scroll-padding-block-start": "",
  "scroll-padding-block-end": "",
  "scroll-padding-bottom": "",
  "scroll-padding-inline": [
    "scroll-padding-inline-start",
    "scroll-padding-inline-end",
  ],
  "scroll-padding-inline-start": "",
  "scroll-padding-inline-end": "",
  "scroll-padding-left": "",
  "scroll-padding-right": "",
  "scroll-padding-top": "",
  "scroll-snap-align": "",
  "scroll-snap-coordinate": "",
  "scroll-snap-destination": "",
  "scroll-snap-points-x": "",
  "scroll-snap-points-y": "",
  "scroll-snap-stop": "",
  "scroll-snap-type": "",
  "scroll-snap-type-x": "",
  "scroll-snap-type-y": "",
  "scroll-timeline": [
    "scroll-timeline-name",
    "scroll-timeline-axis",
  ],
  "scroll-timeline-axis": "",
  "scroll-timeline-name": "",
  "shape-image-threshold": "",
  "shape-margin": "",
  "shape-outside": "",
  "tab-size": "",
  "table-layout": "",
  "text-align": "",
  "text-align-last": "",
  "text-combine-upright": "",
  "text-decoration": [
    "text-decoration-line",
    "text-decoration-style",
    "text-decoration-color",
    "text-decoration-thickness",
  ],
  "text-decoration-color": "",
  "text-decoration-line": "",
  "text-decoration-skip": "",
  "text-decoration-skip-ink": "",
  "text-decoration-style": "",
  "text-decoration-thickness": "",
  "text-emphasis": [
    "text-emphasis-style",
    "text-emphasis-color",
  ],
  "text-emphasis-color": "",
  "text-emphasis-position": "",
  "text-emphasis-style": "",
  "text-indent": "",
  "text-justify": "",
  "text-orientation": "",
  "text-overflow": "",
  "text-rendering": "",
  "text-shadow": "",
  "text-size-adjust": "",
  "text-transform": "",
  "text-underline-offset": "",
  "text-underline-position": "",
  "text-wrap": "",
  "timeline-scope": "",
  "top": "",
  "touch-action": "",
  "transform": "",
  "transform-box": "",
  "transform-origin": "",
  "transform-style": "",
  "transition": [
    "transition-delay",
    "transition-duration",
    "transition-property",
    "transition-timing-function",
    "transition-behavior",
  ],
  "transition-behavior": "",
  "transition-delay": "",
  "transition-duration": "",
  "transition-property": "",
  "transition-timing-function": "",
  "translate": "",
  "unicode-bidi": "",
  "user-select": "",
  "vertical-align": "",
  "view-timeline": [
    "view-timeline-name",
    "view-timeline-axis",
  ],
  "view-timeline-axis": "",
  "view-timeline-inset": "",
  "view-timeline-name": "",
  "view-transition-name": "",
  "visibility": "",
  "white-space": "",
  "white-space-collapse": "",
  "widows": "",
  "width": "",
  "will-change": "",
  "word-break": "",
  "word-spacing": "",
  "word-wrap": "",
  "writing-mode": "",
  "z-index": "",
  "zoom": "",
}  
